### ISSUE TITLE
Option to disable locals function

### ISSUE THREAD

**Issue by misaka00251** [posthtml/posthtml-modules#67]
I'm making a project using Golang with HTML templates, and I use this plugin to simplify my development work. Nice project!

But, in golang we have something called "Template Actions":

```
<!-- from navbar.html -->
{{if .Username}}
<li class="nav-item">
    <a class="nav-link" href="/upload">Upload</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="/settings">Settings</a>
</li>
{{else}}
<li class="nav-item">
    <a class="nav-link" href="/register">Sign Up</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="/login">Log In</a>
</li>
{{end}}
```

And when building HTML, this will cause an error:

```
SyntaxError: SyntaxError: Unexpected token '.'
    at placeholders (C:\edge\node_modules\posthtml-expressions\lib\placeholders.js:62:19)
    at C:\edge\node_modules\posthtml-expressions\lib\index.js:185:14
    at Array.reduce (<anonymous>)
    at walk (C:\edge\node_modules\posthtml-expressions\lib\index.js:172:27)
    at C:\edge\node_modules\posthtml-expressions\lib\index.js:216:22
    at Array.reduce (<anonymous>)
    at walk (C:\edge\node_modules\posthtml-expressions\lib\index.js:172:27)
    at C:\edge\node_modules\posthtml-expressions\lib\index.js:216:22
    at Array.reduce (<anonymous>)
    at walk (C:\edge\node_modules\posthtml-expressions\lib\index.js:172:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edge@0.0.1 build:html: `posthtml -c posthtml.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edge@0.0.1 build:html script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is my config:

```
"posthtml-modules": {
            "root": "./src/views",
            "initial": true
        }
```

Add an option like `disablelocal` will be nice.

**Comment by cossssmin** [comment]
In your code it's caused by this:

```
{{if .Username}}
```

`posthtml-modules` uses `posthtml-expressions` to evaluate expressions in `{{ }}`, and what happens is that it sees a dot in front of something that it will try to evaluate, thuse the `unexpected token` SyntaxError.

Ignore the expression like this:

```
@{{if .Username}}
```

Documentation:

https://github.com/posthtml/posthtml-expressions#ignoring-expressions

**Comment by misaka00251** [comment]
Ah! thank you very much.
